# -*- coding: utf-8 -*-
"""Task1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLE-gK_weNFfvZzvzPV6GRjQJkGWjm8k
"""

def triple_and (a, b, c):
    return a and b and c
a=input("Enter value for a (True/False): ")
b=input("Enter value for a (True/False): ")
c=input("Enter value for a (True/False): ")
result=triple_and(a,b,c)
print(result)

from collections import Counter
l=[]
text = input("Enter a string: ")
for i in text:
  l.append(i)
sorted_text=sorted(l)
print(sorted_text)
print(Counter(text))

def is_hill_number(n):
    digits = str(num)
    i = 0
    l = len(digits)

    while i + 1 < l and digits[i] < digits[i+1]:
        i = i + 1

    if i == 0 or i == l - 1:
        return False

    while i + 1 < l and digits[i] > digits[i+1]:
        i = i + 1

    return i == l - 1


num = input("Enter a number: ")

if is_hill_number(num):
    print(num,"is a Hill Number.")
else:
    print(num,"is NOT a Hill Number.")

text = input("Enter a string: ")
chars = list(text)
n = len(chars)

for i in range(n):
    k = i
    for j in range(i + 1, n):
        if chars[j] < chars[k]:
            k = j
    chars[i], chars[k] = chars[k], chars[i]

print("Sorted string:", ''.join(chars))

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)


num = int(input("Enter a number: "))
print("Fibonacci of", num, "is", fibonacci(num))

s1 = input("Enter first string: ").replace(" ", "").lower()
s2 = input("Enter second string: ").replace(" ", "").lower()

if sorted(s1) == sorted(s2):
    print("'",s1,"' and '",s2,"' are anagrams.")
else:
    print("'",s1,"' and '",s2," are NOT anagrams.")

n = int(input("Enter the number of terms: "))

a, b = 0, 1
count = 0

print("Fibonacci Sequence:")
while count < n:
    print(a, end=" ")
    a, b = b, a + b
    count += 1

text = input("Enter the string: ")
n = int(input("Enter the value of n: "))

length = len(text)

if length % n != 0:
    print("Error: The string cannot be evenly divided into parts of", n, "characters.")
else:
    parts = []
    i = 0
    while i < length:
        part = text[i:i+n]
        parts.append(part)
        i = i + n

    same = True
    for part in parts:
        if part != parts[0]:
            same = False

    if same:
        print("Output:", parts)
    else:
        print("Error: The parts do not have the same sequence of characters.")

alphabet = "abcdefghijklmnopqrstuvwxyz"

text = input("Enter the string to encrypt: ")
shift = int(input("Enter the shift value: "))

result = ""

for ch in text:
    if ch.lower() in alphabet:
        position = alphabet.index(ch.lower())
        new_position = (position + shift) % 26
        new_letter = alphabet[new_position]

        if ch.isupper():
            new_letter = new_letter.upper()

        result = result + new_letter
    else:
        result = result + ch

print("Encrypted string:", result)

card_number = input("Enter card number: ")

digits = [int(d) for d in card_number if d.isdigit()]
digits.reverse()

total = 0
for i in range(len(digits)):
    d = digits[i]
    if i % 2 == 1:
        d = d * 2
        if d > 9:
            d = d - 9
    total = total + d

if total % 10 == 0:
    print("Valid card number")
else:
    print("Invalid card number")

text = input("Enter your text: ")

letter_count = 0
for ch in text:
    if ch.isalpha():
        letter_count = letter_count + 1

words = text.split()
word_count = len(words)

sentence_count = 0
for ch in text:
    if ch == "." or ch == "!" or ch == "?":
        sentence_count = sentence_count + 1

if word_count == 0:
    print("Please enter some text with at least one word.")
else:
    L = (letter_count / word_count) * 100

    S = (sentence_count / word_count) * 100

    CLI = 0.0588 * L - 0.296 * S - 15.8

    print("\nLetters:", letter_count)
    print("Words:", word_count)
    print("Sentences:", sentence_count)
    print("Coleman-Liau Index:", round(CLI, 2))
    print("Approximate Grade Level:", round(CLI))

# Program to print Diamond Pattern and Butterfly Pattern

n = int(input("Enter a number: "))

print("\n----- Diamond Pattern -----")

# Upper half (1 star up to n stars)
i = 1
while i <= n:
    j = 1
    while j <= (n - i):
        print(" ", end="")
        j = j + 1
    k = 1
    while k <= i:
        print("*", end=" ")
        k = k + 1
    print()
    i = i + 1

# Repeat the n-star line one more time (so it appears twice)
k = 1
while k <= n:
    print("*", end=" ")
    k = k + 1
print()

# Lower half (n-1 stars down to 1 star)
i = n - 1
while i >= 1:
    j = 1
    while j <= (n - i):
        print(" ", end="")
        j = j + 1
    k = 1
    while k <= i:
        print("*", end=" ")
        k = k + 1
    print()
    i = i - 1

n = int(input(" enter the value of n: "))

total_cols = 2 * n - 1

for i in range(total_cols):
    if i < n:
        stars = i + 1
    else:
        stars = total_cols - i

    spaces = total_cols - (2 * stars)

    if spaces > 0:
        print("*" * stars + " " * spaces + "*" * stars)
    else:
        print("*" * total_cols)

from abc import ABC,abstractmethod
class Shape(ABC):
    def __init__(self,c):
        self.color=c

    def get_color(self):
        return self.color

    @abstractmethod
    def get_area(self):
        pass

class Square(Shape):
    def __init__(self,c,side):
        super().__init__(c)
        self.side=side

    def get_area(self):
        return float(self.side*self.side)

my_square = Square("Green", 4)

print(f"Color: {my_square.get_color()}")
print(f"Area: {my_square.get_area()}")

arr=[]
n= int(input("Enter the number of numbers in the array here: "))
for i in range(0,n):
    arr.append((int(input("Enter the numbers here: "))))
print("This is the array : ",arr)



def repeated_number(arr):

    for i in range(0,len(arr)):
        for j in range(i+1,n):
            if arr[j]==arr[i]:
                return i

print("The repeated number is first at index",repeated_number(arr))

n = int(input("Enter the size n of the matrix: "))

matrix =[]
for i in range(n):
    row = input(f"Enter row {i+1} ({n} numbers separated by spaces:) ").split()
    row = [int(x) for x in row]
    matrix.append(row)
for i in range(0, n - 1):
    for j in range(i + 1, n):
        matrix[i][j],matrix[j][i] = matrix[j][i],matrix[i][j]
for row in matrix:
    row.reverse()
    print(row)
top, bottom, left, right = 0, n-1, 0, n-1
result = []

while top <=bottom and left <= right:
    for col in range(left, right + 1):
        result.append(matrix[top][col])
    top += 1

    for row in range(top, bottom + 1):
        result.append(matrix[row][right])
    right -= 1

    if top <= bottom:
        for col in range(right, left - 1, -1):
            result.append(matrix[bottom][col])
        bottom -= 1

    if left <= right:
        for row in range(bottom, top - 1, - 1):
            result.append(matrix[row][left])
        left += 1

print(result)